"use strict";
let string1 = "hello";
let string2 = "world";
console.log("I predict false!", string1 == string2);
console.log("I predict true!", string1 != string2);
let word1 = "HELLO";
let word2 = "hello";
console.log("I predict true!", word1.toLowerCase() === word2.toLowerCase());
let Number1 = 10;
let Number2 = 5;
console.log("I predict true!", Number1 > Number2);
console.log("I predict false!", Number1 <= Number2);
let a = 5;
let b = 10;
let c = 15;
console.log("I predict true!", a < b && b < c);
console.log("I predict true!", a < b || b > c);
let fruit = ["Apple", "banana", "Mango"];
console.log("I predict true!", fruit.includes("banana"));
console.log("I predict false!", fruit.includes("grapes"));
