let string1: string = "hello";
let string2: string = "world";
console.log("I predict false!", string1 == string2);
console.log("I predict true!", string1 != string2);
let word1: string = "HELLO";
let word2: string = "hello";
console.log("I predict true!", word1.toLowerCase() === word2.toLowerCase());
let Number1: number = 10;
let Number2: number = 5;
console.log("I predict true!", Number1 > Number2);
console.log("I predict false!", Number1 <= Number2);
let a: number = 5;
let b: number = 10;
let c: number = 15;
console.log("I predict true!",a < b && b < c);
console.log("I predict true!", a < b || b > c);
let fruit: string[] = ["Apple", "banana", "Mango"];
console.log("I predict true!", fruit.includes("banana"));
console.log("I predict false!", fruit.includes("grapes"));