let car = 'subaru';
console.log("Is Car == 'subaru?' I Predict True");
console.log(car == 'subaru');
console.log("Is Car == 'Toyota?' I Predict False");
console.log(car == 'Toyota');
console.log("Is Car != 'Honda?' I Predict True");
console.log(car != 'Honda');
console.log("Is Car == 'Subaru?' I Predict False");
console.log(car == 'Subaru');
console.log("Is Car != 'undefined?' I Predict True");
console.log(car != undefined);
console.log("Is Car == 'null?' I Predict False");
console.log(car == null);
console.log("Is Car === 5? I Predict False");
console.log(car === '5');
console.log("Is Car < z? I Predict True");
console.log(car < 'z');
console.log("Is Car > a? I Predict True");
console.log(car > 'a');
console.log("Does Car Start With 'sab?' I Predict False");
console.log(car.startsWith('sab'));
